FROM node:20-alpine

WORKDIR /app

COPY front-end/package*.json ./

RUN npm install

COPY front-end/ ./

EXPOSE 5175

ENV HOST=0.0.0.0
ENV PORT=5175

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
